version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./sql_scripts:/docker-entrypoint-initdb.d/
            - ./php/src:/var/www/html/  
        ports:
            - 8000:80

    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: jyothika123
            MYSQL_DATABASE: AdmissionForm
            MYSQL_USER: jyothika
            MYSQL_PASSWORD: jyothika123
        ports:
            - "9906:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db